### PR TITLE
Kotlin implementation

### PR DESCRIPTION
**Pull request by kevinxmorales**
This PR implements the Sqids spec in Kotlin. This also adds all the unit tests and github actions to run those tests on push and PR creation

### CODE REVIEW

**Comment by 4kimov** [comment]
Hi @kevinxmorales, this is great, thank you. I've invited you to be the maintainer of this repo, so feel free to push as you please.

Is there anything else left to do, or is this ready & I should update the site?

**Comment by kevinxmorales** [comment]
We'll need to get this set up in Maven central repository so it can be pull into projects. I'll work on getting that set up and let you know when that is ready and the library/artifact is available there.

**Comment by 4kimov** [comment]
Hi @kevinxmorales, what's the ETA on Maven? Kotlin looks almost done, would love to update the website soon.

**Comment by kevinxmorales** [comment]
We have a few options
We can get into the org.sqids org on maven central. I see the maintainer of sqids-scala got this set up already and that there is a similar discussion happening for getting sqids-java published. We can get this published in that maven org and namespace it as sqidskotlin so the imports would be `import org.sqids.sqidskotlin`. If it is desired to all be in the same maven org for consistency, I'll have to work with @jesperoman to get that done. 
The other option is to use github as the repository. We can use jitpack to published versioned library jars to github and have users reference the library as `import com.github.sqidskotlin.sqids`. The downside is that jitpack is less popular than maven for searching dependencies and requires tweaking some project params to download from github instead of maven. Its not difficult, but it is an extra config step for users. I can test this on my fork of the project and get a working version and see if its viable. 
I'm leaning towards working to get his on maven, but it requires some help from the sqids-scala maintainer unless you also have permissions to access the maven org.

**Comment by jesperoman** [comment]
I can help you, if you give me your sonatype username, I can send in a request to add you to the repo!

**Comment by kevinxmorales** [comment]
Thank you, my sonatype username is my github username `kevinxmorales` and email is `kevinm2052@gmail.com` if you need that too

**Comment by 4kimov** [comment]
I'll update the site so people can find the repo.

@jesperoman If you could invite @kevinxmorales in the meantime, that'd be great!

**Comment by jesperoman** [comment]
I've filed an issue with sonatype for adding publishing rights for kevinxmorales, will let you know when it's done!

**Comment by jesperoman** [comment]
According to sonatype, there is no `kevinxmorales` registered to sonatype, @kevinxmorales you need to register there first!

**Comment by kevinxmorales** [comment]
@jesperoman sorry about the delay, it was my misunderstanding on sonatype usernames. My username is kevinm2052@gmail.com. Thank you for taking the time to help get me added to this.

**Comment by jesperoman** [comment]
Now permissions is granted for ```kevinm2052@gmail.com```, happy publishing!

**Pull request merged**
